services:
  vault:
    image: hashicorp/vault:1.18
    container_name: ${COMPOSE_PROJECT_NAME}_vault
    restart: no
    ports:
      - "8200:8200"
    env_file:
      - .env # Contains VAULT_ADDR, VAULT_LICENSE
    cap_add:
      - IPC_LOCK
    command: server -dev -dev-root-token-id=root

  ldap:
    image: osixia/openldap:1.5.0
    container_name: ${COMPOSE_PROJECT_NAME}_ldap
    environment:
      LDAP_ORGANISATION: "Example Inc."
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "admin"
#    ports:
#      - "389:389"
#      - "636:636"

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: ${COMPOSE_PROJECT_NAME}_phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
    ports:
      - "6443:443"

  ldap2:
    image: osixia/openldap:1.5.0
    container_name: ${COMPOSE_PROJECT_NAME}_ldap2
    environment:
      LDAP_ORGANISATION: "Example 2 Inc."
      LDAP_DOMAIN: "example2.com"
      LDAP_ADMIN_PASSWORD: "admin"

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}
