# https://taskfile.dev
version: '3'

env:
  VAULT_ADDR: http://localhost:8200
  VAULT_TOKEN: root

tasks:
  all:
    cmds:
      - task: up
      - task: status
      - sleep 5
      - task: post-install

  up:
    preconditions:
      - test -f docker-compose.yml
      - docker info
    cmds:
      - docker compose up -d --pull=missing
      - sleep 5
      - |
        echo "Vault: http://localhost:8200"
        echo "PHPLDAPAdmin: https://localhost:6443"
    silent: true

  down:
    cmds:
      - task: stop

  restart:
    cmds:
      - docker compose restart vault

  rebuild:
    cmds:
      - task: clean
      - sleep 5
      - task: all
#      - ./scripts/10_vault_vars.sh

  status:
    cmds:
      - vault status

  backup:
    cmds:
      - vault operator raft snapshot save backup-`date +"%Y%m%d-%H%M"`.snap

  rm:
    aliases: ["clean"]
    cmds:
      - docker compose rm -sfv
      - rm terraform.tfstate || true
    ignore_error: true
    vars:
      STACK_NAME:
        sh: basename "`pwd`"

  logs-vault:
    cmds:
      - docker compose logs -f vault

  logs:
    cmds:
      - docker compose logs -f

  stop:
    cmds:
      - docker compose stop
  ui:
    cmds:
      - open http://localhost:8200
      - ./scripts/10_vault_vars.sh
#      - open https://localhost:6443
      - |
        echo "PHPLDAPAdmin: https://localhost:6443"
        echo "bind dn: cn=admin,dc=example,dc=com"

  ldap-config:
    cmds:
      - docker cp ./files/ldap-example.ldif {{ .STACK_NAME }}_ldap:/tmp/ldap-example.ldif
      - docker compose exec ldap /bin/bash -c 'ldapadd -cx -D "cn=admin,dc=example,dc=com" -w admin -f /tmp/ldap-example.ldif'|| true
    vars:
      STACK_NAME:
        sh: basename "`pwd`"

  post-install:
    cmds:
      - task: ldap-config
      - terraform init
      - terraform apply -auto-approve

  rotate-alice:
    desc: rotate alice ldap credentials via static role
    cmds:
      - vault write -f ldap/rotate-role/alice
      - echo "alice credentials rotated successfully"
      - vault read ldap/static-cred/alice

  dynamic-creds:
    desc: fetch dynamic ldap developer credentials
    cmds:
      - vault read ldap/creds/developer

  test:secrets:
    desc: run validation tests for ldap integration
    cmds:
      - echo "fetching dynamic creds for developer role"
      - vault read ldap/creds/developer
      - echo "current creds for static role"
      - vault read ldap/static-cred/alice
      - vault write -f ldap/rotate-role/alice
      - echo "alice credentials rotated successfully"
      - vault read ldap/static-cred/alice

  test:terraform:
    desc: run terraform native tests
    cmds:
      - task: up
      - sleep 10
      - task: status
      - task: ldap-config
      - terraform init
      - sleep 10
      - terraform test
      - task: clean

  test:smoke:
    desc: run smoke tests
    cmds:
      - task: all
      - sleep 10
      - task: test:secrets
