# https://taskfile.dev
version: '3'

env:
  VAULT_ADDR: http://localhost:8200
  VAULT_TOKEN: root

tasks:
  all:
    cmds:
      - task: up
      - task: status
      - sleep 5
      - task: post-install

  up:
    preconditions:
      - test -f docker-compose.yml
      - docker info
    cmds:
      - docker compose up -d --pull=missing
      - sleep 5
      - |
        echo "Vault: http://localhost:8200"
        echo "PHPLDAPAdmin: https://localhost:6443"
    silent: true

  down:
    cmds:
      - task: stop

  restart:
    cmds:
      - docker compose restart vault

  rebuild:
    cmds:
      - task: clean
      - sleep 5
      - task: all
#      - ./scripts/10_vault_vars.sh

  status:
    cmds:
      - vault status
    ignore_error: true

  backup:
    cmds:
      - vault operator raft snapshot save backup-`date +"%Y%m%d-%H%M"`.snap

  rm:
    aliases: ["clean"]
    cmds:
      - docker compose rm -sfv
      - rm terraform.tfstate || true
    ignore_error: true
    vars:
      STACK_NAME:
        sh: basename "`pwd`"

  logs-vault:
    cmds:
      - docker compose logs -f vault

  logs:
    cmds:
      - docker compose logs -f

  stop:
    cmds:
      - docker compose stop
  ui:
    cmds:
      - open http://localhost:8200
      - ./scripts/10_vault_vars.sh
#      - open https://localhost:6443
      - |
        echo "PHPLDAPAdmin: https://localhost:6443"
        echo "bind dn: cn=admin,dc=example,dc=com"

  ldap-config:
    cmds:
      - docker cp ./files/ldap-example.ldif {{ .STACK_NAME }}_ldap:/tmp/ldap-example.ldif
      - docker compose exec ldap /bin/bash -c 'ldapadd -cx -D "cn=admin,dc=example,dc=com" -w admin -f /tmp/ldap-example.ldif'|| true
    vars:
      STACK_NAME:
        sh: basename "`pwd`"

  ldap-vault:
    cmds:
      - ./scripts/20_vault_ldap.sh

  post-install:
    cmds:
      - terraform init
      - terraform apply -auto-approve
      - task: ldap-config

  test:
    cmds:
      - task: clean
      - sleep 5
      - task: up
      - sleep 5
      - terraform test